<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ProductSubCategory.aspx.cs" MaintainScrollPositionOnPostback="true" MasterPageFile="~/AdminEx.Master" Inherits="Admin_CommTrex.ProductSubCategory" %>


<asp:Content ID="contHeadContent" ContentPlaceHolderID="contHeadContent" runat="server">

    <link href="AdminExContent/js/advanced-datatable/css/demo_page.css" rel="stylesheet" />
    <link href="AdminExContent/js/advanced-datatable/css/demo_table.css" rel="stylesheet" />
    <link href="AdminExContent/js/data-tables/DT_bootstrap.css" rel="stylesheet" />

    <!--file upload-->
    <link href="AdminExContent/css/bootstrap-fileupload.min.css" rel="stylesheet" />
    
    <!--tags input-->
    <link href="AdminExContent/js/jquery-tags-input/jquery.tagsinput.css" rel="stylesheet" />
</asp:Content>

<asp:Content ID="CntAdminEx_Header" ContentPlaceHolderID="CntAdminEx_Header" runat="server">
    <div class="page-heading pt">
        <h3>Add/Modify/Delete Product SubCategory</h3>
        <ul class="breadcrumb">
            <li>
                <a href="#">Master </a>
            </li>
            <li class="active">Product SubCategory Master </li>
        </ul>
    </div>
</asp:Content>

<asp:Content ID="CntAdminEx_Body" ContentPlaceHolderID="CntAdminEx_Body" runat="server">
   <asp:HiddenField ID="activeTab" EnableViewState ="true" runat="server" value="addproducts"/>
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading custom-tab ">
                    <ul class="nav nav-tabs">
                        <li class="active" id="tab_addproducts">
                            <a href="#addproductsCategory" data-toggle="tab">Add Product SubCategory</a>
                        </li>
                         <li class="" id="tab_excelimportCategory">
                            <a href="#importproducts" data-toggle="tab">Import SubCategory From Excel</a>
                        </li>
                        <li class="" id="tab_modifyproducts">
                            <a href="#modifyproductsCategory" data-toggle="tab">View/Modify Product SubCategory</a>
                        </li>
                    </ul>
                </header>
                <div class="panel-body">
                    <div class="tab-content">
                        <div class="tab-pane active" id="addproductsCategory">
                            <!-- Naina's Add Product Code Here -->
                            <div class="row">
                                <section class="panel" id="pnlFreeCategoryMaster">
                                    <header class="panel-heading">
                                        Product SubCategory basic details
							                <span class="tools pull-right">
                                                <a href="javascript:;" class="fa fa-chevron-up"></a>
                                                <span class="collapsible-server-hidden">
                                                    <asp:HiddenField runat="server" ID="HiddenField1" EnableViewState="true" Value="c" />
                                                </span>
                                            </span>
                                    </header>
                                    <div class="panel-body collapse">
                                        <div class="form-horizontal adminex-form">
                                            <div class="form-group">
                                                <label class="col-sm-2 col-sm-2 control-label"> ID </label>
                                                <div class="col-sm-10">
                                                    <asp:TextBox ID="txtProductCatID" name="txtSubCatProductCatID" runat="server" CssClass="form-control tooltips" data-trigger="hover" Enabled="false"
                                                        data-toggle="tooltip" title="" placeholder="Autogenerated category id" data-original-title="Generated category code when Product Category is added">
                                                    </asp:TextBox>
                                                </div>
                                            </div>

                                              <div class="form-group">
                                                <label class="col-sm-2 col-sm-2 control-label">Info Selection</label>
                                                <div class="col-sm-10"> 
                                                    <asp:DropDownList ID="cmbInformationType"  runat="server" Font-Bold="True" Enabled="false" AutoPostBack="true" OnSelectedIndexChanged="cmbInformationType_SelectedIndexChanged"  CssClass="form-control m-bot15">
                                                    </asp:DropDownList>
                                                </div>
                                            </div>

                                               <div class="form-group">
                                                <label class="col-sm-2 col-sm-2 control-label">Category Selection</label>
                                                <div class="col-sm-10"> 
                                                    <asp:DropDownList ID="drpCategoryType"  runat="server" Font-Bold="True" Enabled="false" AutoPostBack="true"  CssClass="form-control m-bot15">
                                                    </asp:DropDownList>
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <label class="col-sm-2 col-sm-2 control-label">Prod SubCategory Name</label>
                                                <div class="col-sm-10">
                                                    <asp:TextBox ID="txtProductSubCategoryName" name="txtProductSubCategoryName" runat="server" CssClass="form-control tooltips" data-trigger="hover" data-toggle="tooltip" title="" placeholder="Name of SubCategory" data-original-title="Name of Category">
                                                    </asp:TextBox>
                                                </div>
                                            </div>

                                             <div class="form-group">
                                                <label class="col-sm-2 col-sm-2 control-label">Prod SubCategory Reg Name </label>
                                                <div class="col-sm-10">
                                                    <asp:TextBox ID="txtProductSubCategoryRegional" name="txtProductSubCategoryRegional" runat="server" CssClass="form-control tooltips" data-trigger="hover" data-toggle="tooltip" title="" placeholder="Regional Name of SubCategory" data-original-title="Regional Name of Category"></asp:TextBox>
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <label class="col-sm-2 col-sm-2 control-label">Active Selection</label>
                                                <div class="col-sm-10"> 
                                                    <asp:DropDownList ID="drpIsActive" runat="server" Font-Bold="True" Enabled="false"  CssClass="form-control m-bot15">
                                                        <asp:ListItem Value="-1">Select Activation Type</asp:ListItem>
                                                      <asp:ListItem Value="1"> YES </asp:ListItem>
                                                     <asp:ListItem Value="0"> NO </asp:ListItem>
                                                    </asp:DropDownList>
                                                </div>
                                            </div>

                                             <div class="form-group">
                                                <label class="col-sm-2 col-sm-2 control-label">Image Path </label>
                                                <div class="col-sm-10">
                                                    <asp:TextBox ID="txtImageText" name="txtImageText" runat="server" CssClass="form-control tooltips" data-trigger="hover" data-toggle="tooltip" title="" placeholder="Display an Image Path or Icon Name" data-original-title="Display an Image Path or Icon Name" Enabled="false"></asp:TextBox>
                                                </div>
                                            </div>
                                        
                                            <div class="form-group">
                                                <label class="col-sm-2 col-sm-2 control-label">Select an Image </label>
                                                <div class="col-sm-10">
                                                    <button class="btn gbtns" type="button"
                                                        data-toggle="modal" data-target="#modCatImages" btn-action-image="Class"
                                                        runat="server" id="btnSelectICon">
                                                        <i class="fa fa-folder-open"></i>Browse Customised Images
                                                    </button>
                                                </div>
                                            </div><!--//row buttons -->

                                        </div>
                                        <!--//Form-horizonal-->
                                    </div>
                                    <!--//panel body-->
                                </section>
                                <!--//panel-->
                            </div> <!--//row basic details-->

                            <div class="row">
                                <div class="col-lg-12">
                                    <section class="panel">
                                        <div class="panel-body" style="text-align:center">
                                            <button class="pnl-opener btn gbtn" type="button"
                                                            btn-action="New"  
                                                            data-open-on="Save" data-open-panels="pnlFreeCategoryMaster"
                                                            onserverclick="btnSave_ServerClick"
                                                            runat="server" id="btnSave">
                                                            New <i class="fa fa-plus-square"></i>
                                            </button>
                                            <button class="btn gbtn1" type="button"
                                                            runat="server" id="btnClear" onserverclick="btnClear_ServerClick" >
                                                            Clear <i class="fa fa-refresh"></i>
                                            </button>
                                        </div>
                                        <div class="panel-body">
                                            <div class="alert toss" style="padding: 8px;" runat="server" id="actionInfo">
                                                Press New to add Product SubCategory.
                                            </div>
                                        </div>
                                    </section> <!-- //panel -->
                                </div><!-- //Grid 12 -->
                            </div><!--//row buttons --> 

                        </div> <!--//Add products tab-->



                         <div class="tab-pane" id="importproducts">
                             
                                            <div class="form-group">
                                                <div class="alert toss" style="padding: 8px;" runat="server" id="Div2">
                                                        Press to read data from excel sheet.
                                                </div>
                                            </div>
                                              <div class="form-horizontal adminex-form">
                                                 <div class="form-group">               
                                                           <label class="col-sm-2 col-sm-2 control-label">Select an Excel Sheet: </label>
                                                           <div class="col-sm-10"><asp:FileUpload ID="FileUploadControl1" runat="server" class="default" /></div>
                                                           <br /><br />
                                                     <br />
                                                     <label style="color:red;padding-left: 200px;" class="col-sm-10">*Note : Excel name should be ProductSubCategory.csv</label>
                                                </div>
                                                
                                                <div class="form-group">  
                                                           <label class="col-sm-2 col-sm-2 control-label">Select an Images: </label>
                                                           <div class="col-sm-10" ><input type="file" multiple="multiple" name="fileuploadimages" id="file1" runat="server" /></div>
                                                    <br /><br />       
                                                     <br /><label style="color:red;padding-left: 200px;">*Note : Image size should be between 64X64 and 256X256 pixels.</label>
                                                </div>

                                                <div class="form-group">  
                                                        <div class="col-sm-10"></div>
                                                </div>
                                           </div>
                                        <div class="form-group">  
                                             <div class="panel-body" style="text-align:center">
                                               <button class="btn gbtn" type="button" 
                                                    data-toggle="modal" data-target="#modPasswordBox1"  btn-action-image="Class" 
                                                    runat="server" id="btnImportToExcel">
                                                    <i class="fa fa-table"></i> Import From Excel
                                               </button>
   


                                             </div><%--end of panel-body--%>
                                        </div><%--end of form-group--%>
                           </div>


                             <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="modPasswordBox1" class="modal fade">
       <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
                                            <h4 class="modal-title">SubCategory - (Business)</h4>
                                        </div>
                                        <div class="modal-body">
                                            <%--<form class="form-horizontal" role="form">  --%>                                                 
                                                       <div class="form-group">
                                                            <label for="inputPWd" >Please Input Login Password to proceed : </label>                                                            
                                                            <asp:TextBox TextMode="Password" ID="txtCode" AutoComplete="New-Password" name="txtCode" class="form-control" runat="server"></asp:TextBox><br /><br />
                                                           <label runat="server" id="lblMsgError" style="color:red;" visible="false">* Password is mandatory for upload.</label>
                                                      
                                                      <div class="col-lg-12" style="text-align:center;">
                                                                        <button class="btn gbtn" type="button"
                                                                        runat="server" id="btnImportonPassword"  onserverclick="btnImportonPassword_ServerClick" >
                                                                        <i class="fa fa-upload"></i> Upload
                                                                        </button>
                                                      </div>   
                                                           </div>                                           
                                           <%-- </form>--%>
                                        </div>
                                    </div>
      </div>
      </div>







                        <div class="tab-pane" id="modifyproductsCategory">
                            <div class="form-group">
                                <div class="alert toss" runat="server" id="updateActionDiv">
                                    Click on respective buttons for Modify / Delete.
                                </div>
                            </div>
                            <div class="adv-table nice-scroll-grid">
                                <asp:GridView ID="grdProductSubCategory" runat="server" 
                                    EnableModelValidation="True"  AutoGenerateColumns="False" 
                                    OnRowCancelingEdit="grdProductSubCategory_RowCancelingEdit"         
                                    OnRowEditing="grdProductSubCategory_RowEditing"
                                    EditingControlShowing="grdProductSubCategory_EditingControlShowing"
                                    OnRowUpdating="grdProductSubCategory_RowUpdating"
                                    DataKeyNames="PSC_bIntSubCategoryId" 
                                    RowStyle-CssClass="gradeA"
                                    class="dynamic-table-grid display table table-bordered table-striped">
                                    <Columns>

                                        <asp:TemplateField HeaderText="ID">
                                            <ItemTemplate>
                                                <asp:Label ID="txtSubCatID" runat="server" Text='<%# Eval("PSC_bIntSubCategoryId") %>'></asp:Label>
                                            </ItemTemplate>
                                        </asp:TemplateField>

                                        <asp:TemplateField HeaderText="Information">
                                            <ItemTemplate>
                                                <asp:Label ID="lblInformation" runat="server" Text='<%# Eval("IM_vCharInfoName_En") %>'></asp:Label>
                                                <asp:HiddenField ID="lblInfoID" runat="server" Value='<%# Eval("PC_bIntInformationId") %>'  />
                                                <asp:DropDownList ID="drdlInformation" Visible ="false" AutoPostBack="true" OnSelectedIndexChanged="drdlInformation_SelectedIndexChanged"  runat="server"></asp:DropDownList>
                                             </ItemTemplate>
                                        </asp:TemplateField>

                                          <asp:TemplateField HeaderText="Category">
                                            <ItemTemplate>
                                                <asp:Label ID="lblCategory" runat="server" Text='<%# Eval("PC_vCharCatName") %>'></asp:Label>
                                                <asp:HiddenField ID="HiddenCatID" runat="server" Value='<%# Eval("PSC_bIntCategoryId") %>'  />
                                                <asp:DropDownList ID="drdlCategory" Visible ="false"  runat="server"></asp:DropDownList>
                                             </ItemTemplate>
                                        </asp:TemplateField>

                                        <asp:TemplateField HeaderText=" Product SubCategory Name">
                                            <ItemTemplate>
                                                <asp:Label ID="lblSubCatName" runat="server" Text='<%# Eval("PSC_vCharSubCatName") %>'></asp:Label>
                                            </ItemTemplate>

                                            <EditItemTemplate>
                                                <asp:TextBox ID="txtSubCatName" runat="server" Text='<%# Bind("PSC_vCharSubCatName") %>'>
                                                </asp:TextBox>
                                            </EditItemTemplate>

                                        </asp:TemplateField>
                                        
                                         <asp:TemplateField HeaderText="Product SubCategory Regional Name">
                                            <ItemTemplate>
                                                <asp:Label ID="lblSubRegName" runat="server" Text='<%# Eval("PSC_nVarSubCatName") %>'></asp:Label>
                                            </ItemTemplate>

                                            <EditItemTemplate>
                                                <asp:TextBox ID="txtSubRegName" runat="server" Text='<%# Bind("PSC_nVarSubCatName") %>'>
                                                </asp:TextBox>
                                            </EditItemTemplate>
                                        </asp:TemplateField>

                                        <asp:TemplateField HeaderText="Active">
                                            <ItemTemplate>
                                                <asp:Label ID="lblIsActive"  runat="server" Text='<%# Eval("PSC_bItIsActive") %>'></asp:Label>
                                                <asp:DropDownList ID="drdlActive" Visible="false"  runat="server">
                                                    <asp:ListItem Value="-1">Select Activation Type</asp:ListItem>
                                                    <asp:ListItem Value="1">YES</asp:ListItem>
                                                    <asp:ListItem Value="0">NO</asp:ListItem>
                                                </asp:DropDownList>

                                             </ItemTemplate>
                                            
                                        </asp:TemplateField>

                                       <asp:TemplateField HeaderText="Custom Img">
                                            <ItemTemplate>
                                                <asp:HiddenField ID="imgPath" Value='<%# Eval("PSC_vCharSubCatImgPath") %>' runat="server" />
                                                <asp:HiddenField ID="imgOriginalPath" Value='<%# Eval("PSC_vCharSubCatImgPath") %>' runat="server" />
                                                <asp:Image Width ="40px" Height="40px" ID="ImgCat" runat="server" AlternateText=" " ImageUrl='<%# Eval("PSC_vCharSubCatImgPath") %>' />
                                            </ItemTemplate>
                                        </asp:TemplateField>


                                        <asp:TemplateField HeaderStyle-CssClass="nosort" HeaderText="Selection" ControlStyle-CssClass="column-full-width">
                                            <ItemTemplate>
                                                <div class="btn-group action-buttons-group">
                                                    <button class="btn gbtns" type="button"
                                                        data-toggle="modal" data-target="#modCatImages"
                                                        runat="server" id="btnImage" disabled="disabled"> 
                                                        Browse Img <i class="fa fa-plus-square"></i>
                                                    </button>
                                                </div>
                                            </ItemTemplate>
                                        </asp:TemplateField>

                                        <asp:CommandField ShowEditButton="True" HeaderText="Actions"   HeaderStyle-CssClass="nosort"/>
                                        <asp:TemplateField HeaderStyle-CssClass="nosort" HeaderText="Actions" >
                                            <ItemTemplate>
                                                <a id="A1" class="delete" runat="server"
                                                     data-cat-name='<%# Eval("PC_vCharCatName") %>'
                                                    data-subcat-id='<%# Eval("PSC_bIntSubCategoryId") %>' 
                                                    data-subcat-info='<%# Eval("IM_vCharInfoName_En")%>'
                                                    data-subcat-imgpath='<%# Eval("PSC_vCharSubCatImgPath") %>'
                                                    data-subcat-name='<%# Eval("PSC_vCharSubCatName") %>' href="javascript:;">Delete</a>
                                            </ItemTemplate>
                                        </asp:TemplateField>

                                    </Columns>
                                </asp:GridView>
                            </div>
                            <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="modDeleteConfirm" class="modal fade">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
                                            <h4 class="modal-title">Delete the  Product SubCategory.</h4>
                                        </div>
                                        <div class="modal-body">

                                            <div role="form">
                                                <div class="form-group">
                                                    <h3>Are you sure you want to delete SubCategory with following details?</h3>
                                                </div>
                                                <div class="form-group">
                                                    <div class="row">
                                                        <label class="col-sm-2 col-sm-2 control-label">ID </label>
                                                        <div class="col-sm-10">
                                                            <asp:TextBox ID="txtDelSubCatID" name="txtDelSubCatID" runat="server" CssClass="form-control" Enabled="true"></asp:TextBox>
                                                            <asp:HiddenField ID="txtDelSubCatIDHidden" runat="server" />
                                                        </div>
                                                    </div>
                                                </div> <!-- Id -->
                                                  <div class="form-group">
                                                    <div class="row">
                                                        <label class="col-sm-2 col-sm-2 control-label">Information</label>
                                                        <div class="col-sm-10">
                                                            <asp:TextBox ID="txtDelSubInformation" name="txtDelSubInformation" runat="server" CssClass="form-control" Enabled="true"></asp:TextBox>
                                                        </div>
                                                    </div>
                                                </div> <!-- Id -->

                                                
                                                <div class="form-group">
                                                    <div class="row">
                                                        <label class="col-sm-2 col-sm-2 control-label">Category Name </label>
                                                        <div class="col-sm-10">
                                                            <asp:TextBox ID="txtDelCategory" name="txtDelCategory" runat="server" CssClass="form-control" Enabled="true"></asp:TextBox>
                                                        
                                                        </div>
                                                    </div>


                                                <div class="form-group">
                                                    <div class="row">
                                                        <label class="col-sm-2 col-sm-2 control-label">Sub Category Name </label>
                                                        <div class="col-sm-10">
                                                            <asp:TextBox ID="txtDelSubCatName" name="txtDelSubCatName" runat="server" CssClass="form-control" Enabled="true"></asp:TextBox>
                                                            <asp:HiddenField ID="HiddenDelSubCatPath" runat="server" ></asp:HiddenField>
                                                        </div>
                                                    </div>
                                                </div> <!-- Name -->
                                            

                                                <div class="form-group">
                                                    <div class="row">
                                                        <div class="panel-body" style="text-align: center">
                                                            <button class="btn btn-success" type="button"
                                                                runat="server" id="btnDeleteProduct" onserverclick="btnDeleteProduct_ServerClick"> 
                                                                <i class="fa fa-trash"></i> Delete Category
                                                            </button>
                                                            <button class="btn btn-danger" type="button"
                                                                id="btnCancelDeleteProduct">
                                                                Cancel <i class="fa fa-times-circle"></i>
                                                            </button>
                                                        </div>
                                                    </div>
                                                </div> <!-- Action Buttons -->

                                            </div><!-- //form -->
                                        </div><!-- //modal body -->
                                    </div> <!-- //modal content -->
                                </div> <!-- //modal dialog -->
                            </div> <!-- //dialog -->
                        </div> <!-- Modify product tab-->
                    </div>
                </div>
             </div>
            </section> <!-- Panel Body Main -->
        </div> <!-- Main Row -->


        <div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="modCatImages" class="modal fade" >
        <div class="modal-dialog" style="width:280px;">
            <div class="modal-content">
                <div class="modal-header">
                    <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
                    <h4 class="modal-title">
                        <asp:Label ID="lblimgnm" runat="server" Text="Select Category Images"></asp:Label></h4>
                </div>
                <div class="modal-body">
                    <div role="form">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-9">
                                    <div class="fileupload fileupload-new" data-provides="fileupload" data-caption="Cover Image">
                                        <div class="fileupload-new thumbnail prerview-img-thumb" style="width: 75px; height: 75px;">
                                            <asp:Image ID="MainImage" runat="server" AlternateText="No Image" />
                                        </div>
                                        <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 75px; max-height: 75px; line-height: 20px;"></div>
                                        <div>
                                            <span class="btn btn-default btn-file">
                                                <span class="fileupload-new"><i class="fa fa-picture-o"></i> Select image</span>
                                                <span class="fileupload-exists"><i class="fa fa-undo"></i> Change</span>
                                                <asp:HiddenField ID="txtImgPathMain" runat="server"></asp:HiddenField>
                                                <asp:FileUpload ID="FileMainImage" runat="server" class="default" />
                                            </span>
                                            <a href="#" class="btn btn-danger fileupload-exists" data-dismiss="fileupload"><i class="fa fa-trash"></i> Remove</a>
                                        </div>
                                    </div>
                                    <!-- //file upload-->
                                </div>
                                <!-- //col-md-9-->
                            </div>
                            <!-- //row -->
                        </div>
                        <!-- //form-group -->
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-12" >
                                    <button class="btn gbtn" type="button"
                                        runat="server" id="btnSaveFilePath" onserverclick="btnSaveFilePath_ServerClick">
                                        <i class="fa fa-floppy-o"></i> Save 
                                    </button>
                                    <button class="btn gbtn1" type="button"
                                        runat="server" id="btnSaveFileCancel">
                                       <i class="fa fa-times"></i>  Cancel 
                                    </button>
                                </div>
                            </div>
                             <%--//row--%>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div><%--//Modal ends--%>

</asp:Content>

<asp:Content ID="Cnt_PageLevelScripts" ContentPlaceHolderID="Cnt_PageLevelScripts" runat="server">

      <!--file upload-->
    <script type="text/javascript" src="AdminExContent/js/bootstrap-fileupload.min.js"></script>
    <!--tags input-->
    <script src="AdminExContent/js/jquery-tags-input/jquery.tagsinput.js"></script>
    <script src="AdminExContent/js/tagsinput-init.js"></script>
    <!--bootstrap input mask-->
    <script type="text/javascript" src="AdminExContent/js/bootstrap-inputmask/bootstrap-inputmask.min.js"></script>


    <!--dynamic table-->
    <script type="text/javascript" src="AdminExContent/js/advanced-datatable/js/jquery.dataTables.js"></script>
    <script type="text/javascript" src="AdminExContent/js/data-tables/DT_bootstrap.js"></script>

    <!--font awesome picker creation-->
    <script  type="text/javascript" src="js/pagesjs/Fontawesome.js"></script>

    <!--js for Productcategory initialization -->
    <script src="js/pagesjs/Product_SubCategory.js"></script>">
</asp:Content>
